name: StopECSTasks

# on:
#   repository_dispatch:
#     types: [stop-ecs-task]

on:
    push:
      branches: [ "main" ]

jobs:
  stop_task:
    runs-on: ubuntu-latest

    steps:
      
      - name: Retrieve ECS Cluster and Service Name
        id: get-names
        run: |
            clusters=$(aws ecs list-clusters --query "clusterArns" --output text)
            for cluster_arn in $clusters; do
                cluster_name=$(aws ecs describe-clusters --clusters "$cluster_arn" --query "clusters[0].clusterName" --output text)
                services=$(aws ecs list-services --cluster "$cluster_name" --query "serviceArns" --output text)
                for service_arn in $services; do
                    service_name=$(aws ecs describe-services --cluster "$cluster_name" --services "$service_arn" --query "services[0].serviceName" --output text)
                    echo "::set-output name=cluster::$cluster_name"
                    echo "::set-output name=service::$service_name"
                done
              done


      - name: Stop ECS Task
        run: |
            aws ecs update-service --cluster new_cluster --service new-service --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
