name: StopECSTasks
on:
  push:
    branches: [ "main" ]

jobs:
  stop_task:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve ECS Cluster and Service Names
        id: get-names
        run: |
          # Retrieve cluster and service names
          ecs_info=$(aws ecs list-services --query "serviceArns[0]" --output json)
          cluster_name=$(echo $ecs_info | jq -r '.[] | split("/") | .[1]')
          service_name=$(echo $ecs_info | jq -r '.[] | split("/") | .[2]')

          # Set output variables
          echo "::set-output name=cluster::$cluster_name"
          echo "::set-output name=service::$service_name"

      - name: Stop ECS Tasks
        run: |
          aws ecs update-service --cluster ${{ steps.get-names.outputs.cluster }} --service ${{ steps.get-names.outputs.service }} --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
