name: Stop ECS Task

# on:
#   repository_dispatch:
#     types: [stop-ecs-task]

on:
    push:
      branches: [ "main" ]

jobs:
  stop_task:
    runs-on: ubuntu-latest

    steps:
      - name: Stop ECS Task
        run: |
          aws ecs stop-task --cluster new_cluster --task 7af96c4f369746208582449bd1cfa8e5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
