name: Stop ECS Task

# on:
#   repository_dispatch:
#     types: [stop-ecs-task]

on:
    push:
      branches: [ "main" ]

jobs:
  stop_task:
    runs-on: ubuntu-latest

    steps:
      - name: Stop ECS Task
        run: |
          aws ecs stop-task --cluster new-cluster --task arn:aws:ecs:eu-west-2:440094375133:task/new_cluster/7f34a8dfc7814b668a6c544fe7c1e23e
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
